/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignmentdemolecturer;
import static com.mycompany.assignmentdemolecturer.Main.courseRepo;
import static com.mycompany.assignmentdemolecturer.Main.recordsRepo;
import static com.mycompany.assignmentdemolecturer.Main.userRepo;

import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingUtilities;

public class DeleteUser_admin extends javax.swing.JFrame {
    private String selectedCourse;
    private String userType;
    private Map<String, User> comboItemsMap = new HashMap<>();

    public DeleteUser_admin(String selectedCourse, String userType) {
        initComponents();
        this.selectedCourse = selectedCourse;
        this.userType = userType;
        this.setLocationRelativeTo(null);
        
        // Инициализируем систему через CourseAdministrator
        initializeSystem();
        
        loadUsersComboBox();
        setupCloseLabel();
        updateWindowTitle();
    }
    
    public DeleteUser_admin() {
        this("C101", "Student");
    }
    
    private void initializeSystem() {
        // Используем CourseAdministrator для инициализации
        if (userRepo == null) {
            CourseAdministrator.initializeSystem();
        }
    }
    
    private void updateWindowTitle() {
        jLabel1.setText("Delete " + userType + " - " + selectedCourse);
    }
    
    private void setupCloseLabel() {

    }
    
    private void loadUsersComboBox() {
    jComboBox2.removeAllItems();
    comboItemsMap.clear();
    
    if (userType.equals("Lecturer")) {
        // Для Student и Lecturer загружаем по курсу
        Map<String, User> users = CourseAdministrator.getUsersByCourseAndType(selectedCourse, userType);
        
        if (users.isEmpty()) {
            jComboBox2.addItem("No " + userType + "s available for " + selectedCourse);
            return;
        }
        
        for (User user : users.values()) {
            String displayText = CourseAdministrator.formatUserDisplay(user);
            jComboBox2.addItem(displayText);
            comboItemsMap.put(displayText, user);
        }
    } else if (userType.equals("Student")) {
        // Для Student и Lecturer загружаем по курсу
        Map<String, User> users = CourseAdministrator.getListOfStudentsForSubject(selectedCourse);
        
        if (users.isEmpty()) {
            jComboBox2.addItem("No " + userType + "s available for " + selectedCourse);
            return;
        }
        
        for (User user : users.values()) {
            String displayText = CourseAdministrator.formatUserDisplay(user);
            jComboBox2.addItem(displayText);
            comboItemsMap.put(displayText, user);
        }
    } else if (userType.equals("AcademicOfficer") || userType.equals("CourseAdministrator")) {
        // Для AcademicOfficer и CourseAdministrator загружаем всех (они не привязаны к курсу)
        Map<String, User> users = CourseAdministrator.getUsersByType(userType);
        
        if (users.isEmpty()) {
            jComboBox2.addItem("No " + userType + "s available");
            return;
        }
        
        for (User user : users.values()) {
            String displayText = user.getName() + " (" + user.getEmail() + ")";
            jComboBox2.addItem(displayText);
            comboItemsMap.put(displayText, user);
        }
    }
    
    if (jComboBox2.getItemCount() > 0) {
        jComboBox2.setSelectedIndex(0);
    }
}
    
    
    
    private String buildConfirmationMessage(User user) {
        StringBuilder sb = new StringBuilder();
        sb.append("<html><b>⚠️ Are you sure you want to delete this user?</b><br><br>");
        sb.append("<b>User Details:</b><br>");
        sb.append("• Name: ").append(user.getName()).append("<br>");
        sb.append("• Email: ").append(user.getEmail()).append("<br>");
        sb.append("• Type: ").append(user.getTypeOfUser()).append("<br>");
        
        if (user instanceof Student) {
            Student s = (Student) user;
            sb.append("• Course: ").append(s.getMajor()).append("<br>");
            sb.append("• Year: ").append(s.getYear()).append("<br>");
        } else if (user instanceof Lecturer) {
            Lecturer l = (Lecturer) user;
            sb.append("• Assigned Course: ").append(l.getAssignedCourse()).append("<br>");
        }
        
        sb.append("<br><b>⚠️ Warning:</b> This action cannot be undone!</html>");
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Delete user");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 370, 55));

        jLabel11.setText("jLabel11");
        jLabel11.setAutoscrolls(true);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 77, 52, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Add user");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 72, 181, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Pick a user to delete");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 319, Short.MAX_VALUE))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 580, 150));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Delete user");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, 50));

        Menu.setText("File");

        jMenuItem1.setText("Admin Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem1);

        jMenuItem2.setText("Log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem2);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String selectedText = (String) jComboBox2.getSelectedItem();
    
    if (selectedText == null || selectedText.startsWith("No ")) {
        JOptionPane.showMessageDialog(this, 
            "Please select a user to delete", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Получаем пользователя
    User userToDelete = comboItemsMap.get(selectedText);
    if (userToDelete == null) {
        JOptionPane.showMessageDialog(this, 
            "Selected user not found", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Подтверждение удаления с подробной информацией
    String confirmationMessage = buildConfirmationMessage(userToDelete);
    
    int confirmation = JOptionPane.showConfirmDialog(
        this, 
        confirmationMessage, 
        "⚠️ Confirm User Deletion", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );
    
    if (confirmation == JOptionPane.YES_OPTION) {
        try {
            // Для AcademicOfficer и CourseAdministrator используем пустой курс
            String courseForDeletion = selectedCourse;
            if (userType.equals("AcademicOfficer") || userType.equals("CourseAdministrator")) {
                courseForDeletion = "";
            }
            
            // Используем CourseAdministrator для удаления пользователя
            boolean success = CourseAdministrator.deleteUser(
                userToDelete.getEmail(), 
                courseForDeletion, 
                userType
            );
            
            if (success) {
                String successMessage = "✅ User deleted successfully!\n\n" +
                    "Name: " + userToDelete.getName() + "\n" +
                    "Email: " + userToDelete.getEmail() + "\n" +
                    "Type: " + userToDelete.getTypeOfUser();
                
                // Добавляем информацию о курсе только для Student и Lecturer
                if (userType.equals("Student") || userType.equals("Lecturer")) {
                    successMessage += "\nCourse: " + selectedCourse;
                }
                
                JOptionPane.showMessageDialog(this, 
                    successMessage,
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Обновляем комбобокс
                loadUsersComboBox();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "❌ Failed to delete user", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "❌ Error deleting user: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SwingUtilities.invokeLater(() -> {
            AdminDashboard nc = new AdminDashboard();
            nc.setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CurrentUser.set(null, null, null, null);
        this.dispose();
        
        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUser_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUser_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUser_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUser_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUser_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
