package com.mycompany.assignmentdemolecturer;
import static com.mycompany.assignmentdemolecturer.Main.courseRepo;
import static com.mycompany.assignmentdemolecturer.Main.recordsRepo;
import static com.mycompany.assignmentdemolecturer.Main.userRepo;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        jPasswordField1.setText("");
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        login_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        desc_label = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setEnabled(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(857, 421));
        jPanel1.setMinimumSize(new java.awt.Dimension(857, 421));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 460, 30));

        login_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_label.setText("Login:");
        jPanel1.add(login_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 118, 43));

        password_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_label.setText("Password:");
        jPanel1.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 135, 43));

        login_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 180, 50));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to the course recovery system!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 372, 55));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 760, 110));

        desc_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        desc_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc_label.setText("Login page");
        jPanel1.add(desc_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 158, 64));

        jPasswordField1.setText("jPasswordField1");
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 460, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
            String email = jTextField1.getText() == null ? "" : jTextField1.getText().trim();
                String password = jPasswordField1.getPassword() == null ? "" : new String(jPasswordField1.getPassword());
                if (email.isEmpty() || password.isEmpty()) {
                    JOptionPane.showMessageDialog(Login.this, "Enter email and password!", "Error!", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if (userRepo == null) {
                    JOptionPane.showMessageDialog(Login.this,
                            "Unable to initialize\n" +
                            "Check your Repository for FILLED values!",
                            "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                User user = userRepo.getUser(email);
                if (user == null) {
                    JOptionPane.showMessageDialog(Login.this, "No user with that email!", "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (!user.getPassword().equals(password)) {
                    JOptionPane.showMessageDialog(Login.this, "Wrong password!", "Error!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                CurrentUser.set(user.getEmail(), user.getName(), user.getPassword(), user.getTypeOfUser());
                try {
                    String role = user.getTypeOfUser();
                    if ("Student".equals(role)) {
                        new StudentDashboard().setVisible(true);
                        this.dispose();
                    } 
                    else if ("AcademicOfficer".equals(role)) {
                        new OfficerDashboard().setVisible(true);
                        this.dispose();
                    }
                    else if ("CourseAdministrator".equals(role)) {
                        new AdminDashboard().setVisible(true);
                        this.dispose();
                    }
                    else if ("Lecturer".equals(role)) {
                        new LecturerDashBoard().setVisible(true);
                        this.dispose();
                    }
                    else {this.dispose();}
                } catch (Throwable ex) {
                    JOptionPane.showMessageDialog(Login.this,
                            "Error "+ex.getMessage(),
                            "Error!", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desc_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel login_label;
    private javax.swing.JLabel password_label;
    // End of variables declaration//GEN-END:variables
}
