/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignmentdemolecturer;
import static com.mycompany.assignmentdemolecturer.Main.courseRepo;
import static com.mycompany.assignmentdemolecturer.Main.recordsRepo;
import static com.mycompany.assignmentdemolecturer.Main.userRepo;
import static com.mycompany.assignmentdemolecturer.Main.ACADEMIC_RECORDS_FILE;
import static com.mycompany.assignmentdemolecturer.Main.COURSES_FILE;
import static com.mycompany.assignmentdemolecturer.Main.USERS_FILE;
        import java.util.Map;
        import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
        import javax.swing.table.DefaultTableModel;
        
/**
 *
 * @author muhamedarli
 */
public class OfficerEnrolment extends javax.swing.JFrame {

    /**
     * Creates new form OfficerEnrolment
     */
    public OfficerEnrolment() {
    initComponents();
    loadAtRiskStudents(); // Add this line to constructor
}
    private void loadAtRiskStudents() {
    try {        
        DefaultTableModel model = (DefaultTableModel) TableStudent.getModel();
        model.setRowCount(0);
        
        for (String email : recordsRepo.getRecordsMap().keySet()) {
            Map<String, AcademicRecordItem> courses = recordsRepo.getRecordsMap().get(email);
            
            double totalGPA = 0;
            int courseCount = 0;
            int failedCourses = 0;
            
            for (AcademicRecordItem course : courses.values()) {
                double gpa = course.getGPA();
                totalGPA += gpa;
                courseCount++;
                if (gpa < 2.0) failedCourses++;
            }
            
            double cgpa = courseCount > 0 ? totalGPA / courseCount : 0;
            
            if (cgpa < 2.5 || failedCourses >= 1) {
                User user = userRepo.getUser(email);
                String name = user != null ? user.getName() : email;
                String program = "Unknown";
                String level = "Unknown";
                
                if (user instanceof Student) {
                    Student student = (Student) user;
                    program = student.getMajor();
                    level = student.getYear();
                }
                
                model.addRow(new Object[]{
                    name, email, 
                    program + " - Year " + level,
                    program + " - Year " + getNextLevel(level),
                    String.format("%.2f", cgpa),
                    "Pending"
                });
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading students");
    }
}

private String getNextLevel(String currentLevel) {
    try {
        int currentYear = Integer.parseInt(currentLevel);
        if (currentYear >= 1 && currentYear <= 3) {
            return String.valueOf(currentYear + 1); // 1→2, 2→3, 3→4
        }
        if (currentYear == 4) {
            return "Graduate"; // Year 4 becomes Graduate
        }
    } catch (NumberFormatException e) {
        
    }
    return "Next Level";
}

// Update the existing ButtonSubmitActionPerformed method

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        PanelStudent = new javax.swing.JScrollPane();
        TableStudent = new javax.swing.JTable();
        LabelDecision = new javax.swing.JLabel();
        ComboBoxDecision = new javax.swing.JComboBox<>();
        ButtonSubmit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemDash = new javax.swing.JMenuItem();
        MenuItemEnrol = new javax.swing.JMenuItem();
        MenuItemNot = new javax.swing.JMenuItem();
        MenuItemLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel12.setText("Welcome to Enrolment Approval Window");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        TableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Current Program", "Requested Program", "CGPA", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        PanelStudent.setViewportView(TableStudent);

        LabelDecision.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LabelDecision.setText("Decision:");

        ComboBoxDecision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accept", "Decline" }));
        ComboBoxDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDecisionActionPerformed(evt);
            }
        });

        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        MenuItemDash.setText("Dashboard");
        MenuItemDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDashActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemDash);

        MenuItemEnrol.setText("Enrolment Approval");
        MenuItemEnrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEnrolActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemEnrol);

        MenuItemNot.setText("Notification Center");
        MenuItemNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNotActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNot);

        MenuItemLog.setText("Log out");
        MenuItemLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemLog);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LabelDecision)
                        .addGap(27, 27, 27)
                        .addComponent(ComboBoxDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(PanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDecision)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ComboBoxDecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDecisionActionPerformed
        // TODO add your handling code here:
                                                         
        // Optional: Add any logic when decision is changed
        // For example, enable/disable submit button based on selection
        String decision = (String) ComboBoxDecision.getSelectedItem();
        ButtonSubmit.setEnabled(decision != null);
    
    }//GEN-LAST:event_ComboBoxDecisionActionPerformed

    private void MenuItemDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDashActionPerformed
        // TODO add your handling code here:
         OfficerDashboard dashboard = new OfficerDashboard();
        dashboard.setVisible(true);
        this.dispose();
        // Dashboard menu item - refresh data

    }//GEN-LAST:event_MenuItemDashActionPerformed

    private void MenuItemEnrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEnrolActionPerformed
        // TODO add your handling code here:
        loadAtRiskStudents();
        JOptionPane.showMessageDialog(this, "Refreshed student list.");

    }//GEN-LAST:event_MenuItemEnrolActionPerformed

    private void MenuItemNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNotActionPerformed
        // TODO add your handling code here:
         OfficerNotification notification = new OfficerNotification();
        notification.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemNotActionPerformed

    private void MenuItemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogActionPerformed
        CurrentUser.set(null, null, null, null);
        this.dispose();
        
        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        });

    }//GEN-LAST:event_MenuItemLogActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = TableStudent.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student first.");
        return;
    }
    
    String decision = (String) ComboBoxDecision.getSelectedItem();
    String studentEmail = (String) TableStudent.getValueAt(selectedRow, 1);
    String studentName = (String) TableStudent.getValueAt(selectedRow, 0);
    
    try {
        if ("Accept".equals(decision)) {
            // CHECK CGPA BEFORE ACCEPTING
            String cgpaStr = (String) TableStudent.getValueAt(selectedRow, 4);
            double studentCGPA = Double.parseDouble(cgpaStr);

            if (studentCGPA < 2.0) {
                JOptionPane.showMessageDialog(this, 
                    "Cannot accept " + studentName + "!\n" +
                    "CGPA: " + cgpaStr + " is below 2.0\n" +
                    "Only 'Decline' is allowed for low GPA students.",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return; // STOP HERE - Don't accept
            }

            User user = userRepo.getUser(studentEmail);
            if (user instanceof Student) {
                Student student = (Student) user;
                student.setYear(getNextLevel(student.getYear()));
                userRepo.saveToFile(USERS_FILE);
                TableStudent.setValueAt("Approved", selectedRow, 5);
                JOptionPane.showMessageDialog(this, studentName + " promoted!");
        }
    } else if ("Decline".equals(decision)) {
            recordsRepo.getRecordsMap().remove(studentEmail);
            recordsRepo.saveToFile(ACADEMIC_RECORDS_FILE);
            DefaultTableModel model = (DefaultTableModel) TableStudent.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, studentName + " declined.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerEnrolment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JComboBox<String> ComboBoxDecision;
    private javax.swing.JLabel LabelDecision;
    private javax.swing.JMenuItem MenuItemDash;
    private javax.swing.JMenuItem MenuItemEnrol;
    private javax.swing.JMenuItem MenuItemLog;
    private javax.swing.JMenuItem MenuItemNot;
    private javax.swing.JScrollPane PanelStudent;
    private javax.swing.JTable TableStudent;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

