/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignmentdemolecturer;
import static com.mycompany.assignmentdemolecturer.Main.userRepo;

import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
/**
 *
 * @author muhamedarli
 */

public class OfficerNotification extends javax.swing.JFrame {
    private void initializeNotificationData() {
        try {

            // Set notification types in combo box
            ComboBoxNotType.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Academic Warning", "Enrolment Status", "Meeting Invitation", "General Announcement" }
            ));
            
            // Load all student emails into "To" combo box
            List<String> studentEmails = new ArrayList<>();
            for (User user : userRepo.getUserMap().values()) {
                if (user instanceof Student) {
                    studentEmails.add(user.getEmail());
                }
            }
            
            // Add "All Students" option at the beginning
            studentEmails.add(0, "All Students");
            
            ComboBoxTo.setModel(new javax.swing.DefaultComboBoxModel<>(
                studentEmails.toArray(new String[0])
            ));
            
            // Clear default text
            TextFieldSubject.setText("");
            TextAreaMessage.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    /**
     * Creates new form OfficerNotification
     */
    public OfficerNotification() {
        initComponents();
        initializeNotificationData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SendNotLabel = new javax.swing.JLabel();
        NotTypeLabel = new javax.swing.JLabel();
        ComboBoxNotType = new javax.swing.JComboBox<>();
        LableTo = new javax.swing.JLabel();
        ComboBoxTo = new javax.swing.JComboBox<>();
        LabelSubject = new javax.swing.JLabel();
        TextFieldSubject = new javax.swing.JTextField();
        LabelMessage = new javax.swing.JLabel();
        PanelMessage = new javax.swing.JScrollPane();
        TextAreaMessage = new javax.swing.JTextArea();
        ButtonSubmit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemDash = new javax.swing.JMenuItem();
        MenuItemEnrol = new javax.swing.JMenuItem();
        MenuItemNot = new javax.swing.JMenuItem();
        MenuItemLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel12.setText("Welcome to Notification Center");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        SendNotLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        SendNotLabel.setText("Send notification");

        NotTypeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        NotTypeLabel.setText("Notification Type:");

        ComboBoxNotType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LableTo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LableTo.setText("To:");

        ComboBoxTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LabelSubject.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LabelSubject.setText("Subject:");

        TextFieldSubject.setText("jTextField1");

        LabelMessage.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        LabelMessage.setText("Message:");

        TextAreaMessage.setColumns(20);
        TextAreaMessage.setRows(5);
        PanelMessage.setViewportView(TextAreaMessage);

        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        MenuItemDash.setText("Dashboard");
        MenuItemDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDashActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemDash);

        MenuItemEnrol.setText("Enrolment Approval");
        MenuItemEnrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEnrolActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemEnrol);

        MenuItemNot.setText("Notification Center");
        MenuItemNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNotActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNot);

        MenuItemLog.setText("Log out");
        MenuItemLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemLog);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 36, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SendNotLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NotTypeLabel)
                            .addGap(16, 16, 16)
                            .addComponent(ComboBoxNotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LableTo)
                            .addGap(142, 142, 142)
                            .addComponent(ComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelSubject)
                            .addGap(101, 101, 101)
                            .addComponent(TextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelMessage)
                            .addGap(89, 89, 89)
                            .addComponent(PanelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(ButtonSubmit)))
                    .addGap(0, 58, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 357, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 148, Short.MAX_VALUE)
                    .addComponent(SendNotLabel)
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NotTypeLabel)
                        .addComponent(ComboBoxNotType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LableTo)
                        .addComponent(ComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelSubject)
                        .addComponent(TextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelMessage)
                        .addComponent(PanelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(ButtonSubmit)))
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDashActionPerformed
        // TODO add your handling code here:
        // Dashboard menu item - refresh data
        OfficerDashboard dashboard = new OfficerDashboard();
        dashboard.setVisible(true);
        this.dispose(); 

    }//GEN-LAST:event_MenuItemDashActionPerformed

    private void MenuItemEnrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEnrolActionPerformed
        // TODO add your handling code here:
         OfficerEnrolment enrolment = new OfficerEnrolment();
        enrolment.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_MenuItemEnrolActionPerformed

    private void MenuItemNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNotActionPerformed
        // TODO add your handling code here:
        initializeNotificationData();
        JOptionPane.showMessageDialog(this, "Notification Center refreshed!");
        
    }//GEN-LAST:event_MenuItemNotActionPerformed

    private void MenuItemLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogActionPerformed
        CurrentUser.set(null, null, null, null);
        this.dispose();
        
        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        });

    }//GEN-LAST:event_MenuItemLogActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        // TODO add your handling code here:
        String notificationType = (String) ComboBoxNotType.getSelectedItem();
    String recipient = (String) ComboBoxTo.getSelectedItem();
    String subject = TextFieldSubject.getText().trim();
    String message = TextAreaMessage.getText().trim();
    
    // Validation
    if (notificationType == null || notificationType.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a notification type!", 
            "Validation Error", JOptionPane.WARNING_MESSAGE);
        ComboBoxNotType.requestFocus();
        return;
    }
    
    if (recipient == null || recipient.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a recipient!", 
            "Validation Error", JOptionPane.WARNING_MESSAGE);
        ComboBoxTo.requestFocus();
        return;
    }
    
    if (subject.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a subject!", 
            "Validation Error", JOptionPane.WARNING_MESSAGE);
        TextFieldSubject.requestFocus();
        return;
    }
    
    if (message.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a message!", 
            "Validation Error", JOptionPane.WARNING_MESSAGE);
        TextAreaMessage.requestFocus();
        return;
    }
    
    try {
        // Send real email
        AcademicOfficer userObj = (AcademicOfficer) userRepo.getUserMap().get(CurrentUser.getEmail());
        userObj.sendEmailToStudent(recipient, subject, message);
        
        JOptionPane.showMessageDialog(this, 
            "✅ Email sent successfully!\n\n" +
            "To: " + recipient + "\n" +
            "Subject: " + subject, 
            "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Clear form
        TextFieldSubject.setText("");
        TextAreaMessage.setText("");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "❌ Error: " + e.getMessage() + 
            "\n\nCheck:\n1. Internet connection\n2. Email credentials\n3. JavaMail JAR files", 
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        }
    
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficerNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficerNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficerNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficerNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfficerNotification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JComboBox<String> ComboBoxNotType;
    private javax.swing.JComboBox<String> ComboBoxTo;
    private javax.swing.JLabel LabelMessage;
    private javax.swing.JLabel LabelSubject;
    private javax.swing.JLabel LableTo;
    private javax.swing.JMenuItem MenuItemDash;
    private javax.swing.JMenuItem MenuItemEnrol;
    private javax.swing.JMenuItem MenuItemLog;
    private javax.swing.JMenuItem MenuItemNot;
    private javax.swing.JLabel NotTypeLabel;
    private javax.swing.JScrollPane PanelMessage;
    private javax.swing.JLabel SendNotLabel;
    private javax.swing.JTextArea TextAreaMessage;
    private javax.swing.JTextField TextFieldSubject;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
