/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.assignmentdemolecturer;
import static com.mycompany.assignmentdemolecturer.Main.courseRepo;
import static com.mycompany.assignmentdemolecturer.Main.recordsRepo;
import static com.mycompany.assignmentdemolecturer.Main.userRepo;
import javax.swing.SwingUtilities;

import java.util.Map;

public class UserStatistics extends javax.swing.JDialog {

    /**
     * Creates new form UserStatistics
     */
    public UserStatistics(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent); // Центрируем окно
        setupCloseLabel(); // Настраиваем клик по картинке
    }
    
    private void setupCloseLabel() {

    }
    

    public void loadStatistics() {
        if (userRepo == null) {
            System.out.println("User repository not initialized");
            return;
        }
        
        // Считаем статистику
        int totalUsers = userRepo.getUserCount();
        int students = 0;
        int lecturers = 0;
        int admins = 0;
        int officers = 0;
        
        for (User user : userRepo.getUserMap().values()) {
            String type = user.getTypeOfUser();
            switch (type) {
                case "Student":
                    students++;
                    break;
                case "Lecturer":
                    lecturers++;
                    break;
                case "CourseAdministrator":
                    admins++;
                    break;
                case "AcademicOfficer":
                    officers++;
                    break;
            }
        }
        
        // Устанавливаем значения
        jLabelTotalValue.setText(String.valueOf(totalUsers));
        jLabelAdminsValue.setText(String.valueOf(admins));
        jLabelStudentsValue.setText(String.valueOf(students));
        jLabelLecturersValue.setText(String.valueOf(lecturers));
        jLabelOfficersValue.setText(String.valueOf(officers));
    }
    

    public void loadStatistics(int totalUsers, int students, int lecturers, int admins, int officers) {
        jLabelTotalValue.setText(String.valueOf(totalUsers));
        jLabelAdminsValue.setText(String.valueOf(admins));
        jLabelStudentsValue.setText(String.valueOf(students));
        jLabelLecturersValue.setText(String.valueOf(lecturers));
        jLabelOfficersValue.setText(String.valueOf(officers));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelOfficersValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTotalValue = new javax.swing.JLabel();
        jLabelAdminsValue = new javax.swing.JLabel();
        jLabelStudentsValue = new javax.swing.JLabel();
        jLabelLecturersValue = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User statistics");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 260, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Academic officers:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabelOfficersValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelOfficersValue.setText(".");
        getContentPane().add(jLabelOfficersValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Admins:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Students:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Lecturers:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total number of users:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelTotalValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotalValue.setText(".");
        getContentPane().add(jLabelTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 190, -1));

        jLabelAdminsValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelAdminsValue.setText(".");
        getContentPane().add(jLabelAdminsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, -1));

        jLabelStudentsValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStudentsValue.setText(".");
        getContentPane().add(jLabelStudentsValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 190, -1));

        jLabelLecturersValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelLecturersValue.setText(".");
        getContentPane().add(jLabelLecturersValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, -1));

        adminMenu.setText("File");

        jMenuItem1.setText("Admin Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem1);

        jMenuItem2.setText("Log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        adminMenu.add(jMenuItem2);

        jMenuBar1.add(adminMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SwingUtilities.invokeLater(() -> {
            AdminDashboard nc = new AdminDashboard();
            nc.setVisible(true);
            this.dispose();
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CurrentUser.set(null, null, null, null);
        this.dispose();

        SwingUtilities.invokeLater(() -> {
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserStatistics dialog = new UserStatistics(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAdminsValue;
    private javax.swing.JLabel jLabelLecturersValue;
    private javax.swing.JLabel jLabelOfficersValue;
    private javax.swing.JLabel jLabelStudentsValue;
    private javax.swing.JLabel jLabelTotalValue;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
